# https://daiderd.com/nix-darwin/manual/index.html
# - nix.settings
# - services
# - environment
# - programs
# - fonts
# - system
# - users.users
{ config, pkgs, lib, ... }:
{
  system.stateVersion = 5;
  system.primaryUser = "jerry";

  nix.enable = false;

  # will apply on nix
  # https://nixos.org/manual/nix/stable/command-ref/conf-file.html
  nix.settings = lib.optionalAttrs config.nix.enable {
    experimental-features = [
      "nix-command"
      "flakes"
      "auto-allocate-uids"
    ];

    # A substituter is an additional store from which Nix can obtain store objects instead of building them
    # https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-substituters
    substituters = [
      "https://cache.nixos.org/"
      "https://mirrors.ustc.edu.cn/nix-channels/store"
      "https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store"
    ];

    trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    ];

    # `admin` is macOS's `wheel` group
    # https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-trusted-users
    trusted-users = [ "@admin" ];

    #auto-optimise-store = true;

    # /etc/nix/nix.conf content generated by
    # https://github.com/DeterminateSystems/nix-installer
    bash-prompt-prefix = "(nix:$name)\040";
    extra-nix-path = "nixpkgs=flake:nixpkgs";

    # on mac chip system, build intel chip too
    # https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-extra-platforms
    extra-platforms = lib.optionals (pkgs.system == "aarch64-darwin") [
      "x86_64-darwin"
      "aarch64-darwin"
    ];
  };

  #nix.optimise.automatic = true;
  # 🤔
  # https://daiderd.com/nix-darwin/manual/index.html#opt-nix.configureBuildUsers
  #nix.configureBuildUsers = true;

  # 🤔 nix-daemon for what?
  # https://daiderd.com/nix-darwin/manual/index.html#opt-services.nix-daemon.enable
  # /Library/LaunchDaemons
  #services.nix-daemon.enable = true;

  # system-wide packages
  # `home-manager` currently has issues adding them to `~/Applications`
  # Issue: https://github.com/nix-community/home-manager/issues/1341
  # appears in /run/current-system/sw
  # automatically available to all users
  # automatically updated every time you rebuild the system configuration.
  environment.systemPackages = [
    # 🤔 https://daiderd.com/nix-darwin/manual/index.html#opt-environment.systemPackages
  ];

  # should disable to avoid conflict with zsh func like copypath
  # nix-index and its command-not-found helper
  # https://daiderd.com/nix-darwin/manual/index.html#opt-programs.nix-index.enable
  programs.nix-index.enable = false;

  # must enable it, so new session can enable nix-env
  # if not enable, system built-in zsh will run without nix
  # https://daiderd.com/nix-darwin/manual/index.html#opt-programs.zsh.enable
  programs.zsh.enable = true;

  # Fonts
  fonts.packages = [
    pkgs.nerd-fonts.jetbrains-mono
    pkgs.nerd-fonts.inconsolata
    pkgs.noto-fonts-cjk-sans
    pkgs.noto-fonts-cjk-serif
  ];

  # https://daiderd.com/nix-darwin/manual/index.html#opt-homebrew.enable
  homebrew = {
    enable = true;
    onActivation.cleanup = "uninstall";
    taps = [
      "messense/macos-cross-toolchains"
      # "emqx/mqttx"
      "supabase/tap"
      "tw93/tap"
      "hashicorp/tap"
    ];
    brews = [
      # zsh plugin manager
      "antidote"
      # "emqx/mqttx/mqttx-cli"
      # "python@3.10"
      "coreutils"
      "gnu-sed"
      "beancount"
      "aarch64-unknown-linux-gnu"
      "ffmpeg"
      # kotlin native develop, pre-build sqlite
      "bdw-gc"
      "m4"
      "libtool"
      "pkg-config"
      "guile"
      "ollama"
      "supabase"
      "mise"
      "cloudflared"
      "tw93/tap/mole"
      "bitwarden-cli"
      "duti"
      "chezmoi"
      "kind"
      "terraform"
      "gnupg"
      "iproute2mac"
    ];
    casks = [
      "anki"
      "calibre"
      "google-chrome"
      "iterm2"
      "logseq"
      "microsoft-remote-desktop"
      "snipaste"
      "squirrel-app"
      # "tor-browser"
      "visual-studio-code"
      "syncthing-app"
      #"firefox"
      # "iina"
      "android-platform-tools"
      "keka"
      # "arc"
      # "maccy"
      "pearcleaner"
      "localsend"
      # "nimble-commander"
      "kap"
      # "utm"
      "warp"
      # "wireshark"
      "jordanbaird-ice"
      # "msty"
      "soulseek"
      # "genymotion"
      "balenaetcher"
      # "flutter"
      "vlc"
      "google-drive"
      "raycast"
      "clash-verge-rev"
      "obsidian"
      "orbstack"
      # "videofusion"
      # "spotify"
      # "wechat"
      # "tencent-meeting"
      "rectangle"
      "rustdesk"
      "zoom"
      "sourcetree"
      "bitwarden"
      "zed"
      "android-studio"
      "antigravity"
      "headlamp"
      "claude-code"
      "caffeine"
      "emacs-app"
    ];
  };

  # macOS system tweaking
  # Keyboard
  system.keyboard.enableKeyMapping = true;
  system.keyboard.remapCapsLockToEscape = true;

  # only specify home directory
  # will automatically create user? 🤔
  # https://daiderd.com/nix-darwin/manual/index.html#opt-users.users
  users.users."jerry" = {
    home = "/Users/jerry";
  };
}
